name: CICD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build
        # assuming you have a .NET solution at the root; modify as needed

  approval-gate:
    runs-on: ubuntu-latest
    environment: 
      name: prod-approval
    needs: build # assuming the approval gate should only run after a successful build
    steps:
      - name: Wait for approval
        run: echo "approved"
        shell: bash
        # this step is just a placeholder for actual approval logic

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: build
    steps:
      - name: Deploy to Prod
        run: echo "Deploying to production"
        # replace with actual deploy commands
      - name: Random Sleep
        run: sleep $((RANDOM % 1000))
        shell: bash

