name: CICD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build
       
  approval-gate:
    runs-on: ubuntu-latest
    environment: 
      name: prod-approval
    needs: build 
    steps:
      - name: Wait for approval
        run: echo "approved"
        shell: bash

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: build
    steps:
      - name: Deploy to Prod
        run: echo "Deploying to production"
      - name: Random Sleep
        run: sleep $((RANDOM % 1000))
        shell: bash

