name: CICD Pipeline
on:
  push:
   branches: [main]
   paths-ignore:
     - .gitignore
     - "Archive/**"
     - "docs/**"
  
  pull_request:
    branches: [main]
    paths-ignore:
      - .gitignore
      - "Archive/**"
      - "docs/**"

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:

  pp-approval-gate:
  #  if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
  
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: leahy268
          minimum-approvals: 1
          issue-title: Approval into PP
          timeout: 1
  
  dummy-job:
    needs: pp-approval-gate
  #  if: github.event_name != 'pull_request'
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: approved
        run: echo "Approved"