name: CICD Pipeline
on:
  push:
   branches: [main]
   paths-ignore:
     - .gitignore
     - "Archive/**"
     - "docs/**"
  
  pull_request:
    branches: [main]
    paths-ignore:
      - .gitignore
      - "Archive/**"
      - "docs/**"

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:

  
  #  if: github.event_name != 'pull_request'
  deploy-pp:
  #  if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: preprod
    concurrency:
      cancel-in-progress: true
      group: preprod
    
    steps:
      - name: approved PreProd
        run: exit 1

  deploy-prod:

    runs-on: ubuntu-latest
    environment: prod
    concurrency:
      cancel-in-progress: true
      group: prod
  