name: CICD Pipeline
on:
  push:
   branches: [main]
   paths-ignore:
     - .gitignore
     - "Archive/**"
     - "docs/**"
  
  pull_request:
    branches: [main]
    paths-ignore:
      - .gitignore
      - "Archive/**"
      - "docs/**"

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:

  
  #  if: github.event_name != 'pull_request'
  deploy-pp:
  #  if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: pp
    concurrency:
      cancel-in-progress: false
      group: preprod
    
    steps:
      - name: approved PreProd
        run: sleep 500

  deploy-prod:

    runs-on: ubuntu-latest
    environment: prod
    concurrency:
      cancel-in-progress: false
      group: prod
    
    needs: deploy-pp

    steps:
      - name: approved Prod
        run: sleep 500
